
invalid_data = 'The Request Contains Invalid Data'
data_created = 'Data Created Successfully'
data_already_exist = 'Data Already Exist'
internal_server_error = 'Internal Server Error'
data_not_found = 'Given Data Not Found'
invalid_password = 'Wrong Password'
login_response = 'Login Success'
data_success = 'Success'
forbidden_response = 'Invalid Credential'
length_zero_error = 'Minimum One Data is Required'
access_denied = 'The Service Access Denied'
